from django.urls import path
from .views import *

urlpatterns = [
    path('', user_login, name='login'),
    path('abonements_list/', abonements_list, name='abonements_list'),
    path('abonements/', abonement_report, name='abonements'),
    path('add_client/', AddClient.as_view(), name='add_client'),
    path('admins_profile/', admins_profile, name='admins_profile'),
    path('add_event/', AddEventView.as_view(), name='add_event'),
    path('client/<tg_id>/', profile_view, name='client'),
    path('clients/', ClientsView.as_view(), name='clientview'),
    path('clients/excel', export_clients_xls, name='export_client'),
    path('documentation/', documentation, name='documentation'),
    path('event_list/', event_list, name='event_list'),
    path('index/', IndexView.as_view(), name='index'),
    path('logout/', user_logout, name="logout"),
    path('offices/', offices_view, name='offices'),
    path('office/<int:pk>', office_detail, name='office_detail'),
    path('office_details_payment/<int:pk>', office_details_payment, name='office_details_payment'),
    path('order_from_profile/', order_from_profile, name='order_from_profile'),
    path('orders/', OrdersView.as_view(), name='orders'),
    path('orders/<int:pk>/update', OrderUpdate.as_view(), name='update'),
    path('order/<order_id>/', order_details, name='ordersDetail'),
    path('orders/excel', export_orders_xls, name='export_excel'),
    path('payments/', paymentsView, name='payments'),
    path('payments/download', ExportExcel.as_view(), name='download'),
    path('products/download', ExportExcelProducts.as_view(), name='download_products'),
    path('products/', product_report, name='products'),
    # path('reports/', payment_report, name='reports'),
    path('sale_subscribtion/', sale_subscribtion, name='sale_subscribtion'),

    path('apiclient/<str:id>/', Clientapiview.as_view()),
    path('api/companies/', CompanyView.as_view()),
    path('api/categories/', CategoryView.as_view()),
    path('api/branches/<int:company_id>', Branchesapiview.as_view()),
    path('api/branchByID/<int:filial_id>', BranchByIDview.as_view()),
    path('api/branchRooms/<int:branch_pk>/', RoomsByFilialView.as_view()),
    path('api/room/<int:room_id>', RoomDetailapiview.as_view()),
    path('api/roomByCat/<int:category_id>', RoomsByCatview.as_view()),
    path('api/roomByBranch/<int:branchPK>', RoomsByBranchview.as_view()),
    path('api/events', Eventsapiview.as_view()),
    path('api/auth/sendOTP', SendOTPView.as_view()),
    path('api/auth/verifyOTP', VerifyOtpView.as_view()),
    path('api/roomByHour/<int:room_id>/<int:hour2>', RoomByHourView.as_view()),
    path('api/auth/client/<str:pk>', ClientChangesView.as_view()),
    path('api/abonements', AbonementView.as_view()),
    path('api/addOrder', OrderCreateAPIView.as_view()),

    # path('pyclick/process/click/transaction/create/', name='click')

]
