# Generated by Django 4.2.1 on 2024-01-23 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': '1 Компании',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория комнаты', 'verbose_name_plural': '3 Категории комнат'},
        ),
        migrations.AlterModelOptions(
            name='filial',
            options={'verbose_name': 'Филиал', 'verbose_name_plural': '2 Филиалы'},
        ),
        migrations.AlterModelOptions(
            name='rooms',
            options={'verbose_name': 'Помещения в филиалах', 'verbose_name_plural': '4 Помещении в филиалах'},
        ),
        migrations.AddField(
            model_name='filial',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.company', verbose_name='Компания'),
        ),
    ]
