# Generated by Django 4.2.1 on 2024-01-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_company_alter_category_options_alter_filial_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/companies/', verbose_name='Фото компании'),
        ),
        migrations.AddField(
            model_name='filial',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес центра'),
        ),
        migrations.AddField(
            model_name='filial',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/branches/', verbose_name='Фото филиала'),
        ),
    ]
