# Generated by Django 4.2.1 on 2024-01-30 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_company_image_filial_address_filial_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'fotki', 'verbose_name_plural': 'Библиотека fotok'},
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='client',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='file',
        ),
        migrations.AddField(
            model_name='gallery',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crm.filial', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/branch', verbose_name='Image'),
        ),
    ]
