# Generated by Django 4.2.1 on 2024-02-10 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_gallery_options_remove_gallery_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='tg_lang',
        ),
    ]
