# Generated by Django 4.2.1 on 2024-04-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_remove_abonement_filial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonement',
            name='other_loc_work_time',
            field=models.PositiveSmallIntegerField(blank=True, default=3, null=True, verbose_name='Возможность работать в других локацих'),
        ),
    ]
