# Generated by Django 4.2.1 on 2024-04-20 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_abonement_other_loc_work_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='summa_with_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма со скидкой'),
        ),
        migrations.AlterField(
            model_name='abonementbuylist',
            name='free_time',
            field=models.SmallIntegerField(default=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)]),
        ),
    ]
