# Generated by Django 4.2.1 on 2024-02-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_remove_client_tg_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='token',
            field=models.TextField(max_length=100, unique=True, verbose_name='ИД клиента'),
        ),
    ]
