# Generated by Django 4.2.1 on 2024-02-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_client_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='token',
        ),
        migrations.AddField(
            model_name='client',
            name='tg_lang',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('ru', 'Russian'), ('uz', 'Uzbek')], default='ru', max_length=10, null=True),
        ),
    ]
