# Generated by Django 4.2.1 on 2024-02-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_remove_client_token_client_tg_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_accept_user',
            field=models.TextField(blank=True, null=True),
        ),
    ]
