# Generated by Django 4.2.1 on 2024-04-25 12:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_abonement_free_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonement',
            name='days',
            field=models.PositiveSmallIntegerField(verbose_name='Срок абонемента/дней'),
        ),
        migrations.AlterField(
            model_name='abonement',
            name='free_time',
            field=models.SmallIntegerField(default=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)], verbose_name='-50% на Митинг рум'),
        ),
    ]
