# Generated by Django 4.2.1 on 2024-03-12 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_order_pay_accept_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricelists',
            options={'verbose_name': 'Прайслист', 'verbose_name_plural': 'Прайслисты'},
        ),
    ]
