# Generated by Django 4.2.1 on 2024-03-20 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_alter_pricelists_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_start_date', models.DateTimeField(verbose_name='Дата ивента')),
                ('title', models.TextField(max_length=255, verbose_name='Заголовка')),
                ('event_description', models.TextField(verbose_name='Описания')),
                ('event_locate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.filial', verbose_name='Адрес ивента')),
            ],
        ),
    ]
