# Generated by Django 4.2.1 on 2024-03-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_events'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name': 'Мероприятия', 'verbose_name_plural': 'Мероприятии'},
        ),
        migrations.AddField(
            model_name='events',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Постер'),
        ),
    ]
